
<!-- インクルードエリア -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="keywords" content="<?php print t::h($page_info['keywords']); ?>" />
<meta name="description" content="<?php print t::h($page_info['description']); ?>" />

<link rel="stylesheet" href="<?php print t::h($px->theme()->href('/common/css/setup.css')); ?>" type="text/css" />
<link rel="stylesheet" href="<?php print t::h($px->theme()->href('/common/css/modules.css')); ?>" type="text/css" />
<link rel="stylesheet" href="<?php print t::h($px->path_theme_files('css/layout.css')); ?>" type="text/css" />

<script src="<?php print t::h($px->theme()->href('/common/js/jquery-1.10.1.min.js')); ?>" type="text/javascript"></script>
<!-- / インクルードエリア -->

